# Generated by Django 6.0.1 on 2026-01-17 01:08

import django.db.models.deletion
import django_fsm
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0002_location'),
        ('core', '0001_enable_pgvector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content_template', models.TextField()),
                ('required_variables', models.JSONField(default=list)),
                ('campaign_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_templates', to='brands.brand')),
            ],
            options={
                'db_table': 'campaign_templates',
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LocationCampaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', django_fsm.FSMField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=50)),
                ('customizations', models.JSONField(default=dict)),
                ('generated_content', models.TextField(blank=True)),
                ('content_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='brands.location')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_campaigns', to='campaigns.campaigntemplate')),
            ],
            options={
                'db_table': 'location_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requested_changes', 'Requested Changes')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='campaigns.locationcampaign')),
            ],
            options={
                'db_table': 'approval_steps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='locationcampaign',
            index=models.Index(fields=['location', 'status'], name='location_ca_locatio_9fefad_idx'),
        ),
        migrations.AddIndex(
            model_name='locationcampaign',
            index=models.Index(fields=['status', 'scheduled_start'], name='location_ca_status_c1ace5_idx'),
        ),
    ]
