# Generated by Django 6.0.1 on 2026-01-23 04:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcampaign',
            name='email_preview_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='locationcampaign',
            name='email_subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='locationcampaign',
            name='generated_html_email',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_recipients', to='campaigns.locationcampaign')),
            ],
            options={
                'db_table': 'email_recipients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='email_recip_campaig_6436aa_idx')],
            },
        ),
    ]
