# Generated by Django 6.0.1 on 2026-01-17 00:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('store_number', models.CharField(max_length=50)),
                ('address', models.JSONField(default=dict)),
                ('attributes', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='brands.brand')),
            ],
            options={
                'db_table': 'locations',
                'ordering': ['brand', 'store_number'],
                'indexes': [models.Index(fields=['brand', 'is_active'], name='locations_brand_i_931e56_idx')],
                'unique_together': {('brand', 'store_number')},
            },
        ),
    ]
