# Generated by Django 6.0.1 on 2026-01-23 04:12

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.JSONField(default=apps.users.models.default_user_preferences),
        ),
    ]
